### ISSUE TITLE
The cocoapods version is 1.7.4, and when I execute the pod trunk command, I report the following error：

### ISSUE THREAD

**Issue by melo30** [CocoaPods/cocoapods-trunk#142]
### Command

```
/Users/chencheng/.rvm/rubies/ruby-2.4.1/bin/pod trunk push MJBUserInfoKit.podspec --allow-warnings --use-libraries
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.7.4
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]
    RubyGems : 2.7.7
        Host : Mac OS X 10.15.1 (19B88)
       Xcode : 11.2.1 (11B53)
         Git : git version 2.21.0
Ruby lib dir : /Users/chencheng/.rvm/rubies/ruby-2.4.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b515bbf3933f4f956141326a3352a3e393330998
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Error

```
NameError - uninitialized constant Pod::TrunkSource
/Users/chencheng/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk/push.rb:147:in `update_master_repo'
/Users/chencheng/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk/push.rb:69:in `run'
/Users/chencheng/.rvm/gems/ruby-2.4.1@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/chencheng/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.7.4/lib/cocoapods/command.rb:52:in `run'
/Users/chencheng/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.7.4/bin/pod:55:in `<top (required)>'
/Users/chencheng/.rvm/rubies/ruby-2.4.1/bin/pod:23:in `load'
/Users/chencheng/.rvm/rubies/ruby-2.4.1/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by igor-makarov** [comment]
Probably could add a different Gemfile to the Travis matrix

**Comment by melo30** [comment]
@dnkoutso @igor-makarov So what you're saying is that the only way to solve this problem is to wait until the release of version 1.4.2 of cocoapod-trunk😂

**Comment by igor-makarov** [comment]
Or you could upgrade CocoaPods to >= 1.8.0.

Or downgrade `cocoapods-trunk` plugin. That's also a solution.

**Comment by melo30** [comment]
> Or you could upgrade CocoaPods to >= 1.8.0.
> 
> Or downgrade `cocoapods-trunk` plugin. That's also a solution.

I solved the problem by downgrade cocoapods-trunk plugin to 1.3.1 , thank you very much!

**Comment by melo30** [comment]
> Or you could upgrade CocoaPods to >= 1.8.0.
> 
> Or downgrade `cocoapods-trunk` plugin. That's also a solution.

But, if i upgrade CocoaPods to >= 1.8.0, Can't solve this problem. First of all, it will report the wrong "CDN: trunk Repo update failed". Then I looked at the common online solution: 1.podfile  add  source 'https://github.com/CocoaPods/Specs.git'  2.pod repo remove trunk .    And then when I went to execute 'pod trunk push ....' , It's going to help me create trunk repo again. And then repeat the mistake：CDN: trunk Repo update failed...   Do you know why this is?
