### ISSUE TITLE
Problem with pod trunk push that receives 422

### ISSUE THREAD

**Issue by ashfurrow** [CocoaPods/cocoapods-trunk#38]
I ran `pod trunk push Moya.podspec` and received the following error:

```
Validating podspec
 -> Moya
[!] The Pod Specification did not pass validation.
```

Running with `--verbose` yielded the following output: 

```
opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established
<- "POST /api/v1/pods HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nAuthorization: Token [My token]]\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nUser-Agent: Ruby\r\nHost: trunk.cocoapods.org\r\nContent-Length: 674\r\n\r\n"
<- "{\"name\":\"Moya\",\"version\":\"0.6\",\"summary\":\"Network abstraction layer written in Swift\",\"homepage\":\"https://github.com/AshFurrow/Moya\",\"license\":{\"type\":\"MIT\",\"file\":\"LICENSE\"},\"authors\":{\"Ash Furrow\":\"ash@ashfurrow.com\"},\"social_media_url\":\"http://twitter.com/ashfurrow\",\"platforms\":{\"ios\":\"8.0\"},\"source\":{\"git\":\"https://github.com/ashfurrow/Moya.git\",\"tag\":\"0.6\"},\"default_subspecs\":\"Core\",\"subspecs\":[{\"name\":\"Core\",\"source_files\":[\"Moya.swift\",\"Endpoint.swift\"],\"dependencies\":{\"Alamofire\":[\"~> 1.1.0\"]},\"frameworks\":\"Foundation\"},{\"name\":\"Reactive\",\"source_files\":[\"Moya+ReactiveCocoa.swift\",\"RACSignal+Moya.swift\"],\"dependencies\":{\"Moya/Core\":[],\"ReactiveCocoa\":[]}}]}\n"
-> "HTTP/1.1 422 \r\n"
-> "Date: Sun, 11 Jan 2015 15:32:27 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 170\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin 1.6.2 codename Doc Brown\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 170 bytes...
-> "{\"error\":\"The Pod Specification did not pass validation.\",\"data\":{\"warnings\":[\"A value for `requires_arc` should be specified until the migration to a `true` default.\"]}}"
read 170 bytes
Conn keep-alive
[!] The Pod Specification did not pass validation.

/Users/ash/.rvm/gems/ruby-2.1.2/gems/cocoapods-trunk-0.5.0/lib/pod/command/trunk.rb:69:in `print_error'
/Users/ash/.rvm/gems/ruby-2.1.2/gems/cocoapods-trunk-0.5.0/lib/pod/command/trunk.rb:28:in `request_url'
/Users/ash/.rvm/gems/ruby-2.1.2/gems/cocoapods-trunk-0.5.0/lib/pod/command/trunk.rb:34:in `request_path'
/Users/ash/.rvm/gems/ruby-2.1.2/gems/cocoapods-trunk-0.5.0/lib/pod/command/trunk/push.rb:57:in `run'
/Users/ash/.rvm/gems/ruby-2.1.2/gems/claide-0.8.0/lib/claide/command.rb:312:in `run'
/Users/ash/.rvm/gems/ruby-2.1.2/bundler/gems/CocoaPods-0740ff3a8310/lib/cocoapods/command.rb:45:in `run'
/Users/ash/.rvm/gems/ruby-2.1.2/bundler/gems/CocoaPods-0740ff3a8310/bin/pod:43:in `<top (required)>'
/Users/ash/.rvm/gems/ruby-2.1.2/bin/pod:23:in `load'
/Users/ash/.rvm/gems/ruby-2.1.2/bin/pod:23:in `<main>'
/Users/ash/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/ash/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

I'd expect that the `warnings` array would be printed, but it looks like something might be wrong in `print_error`. 

Let me know what else I can provide to help.

**Comment by orta** [comment]
Thanks! It should be sorted with https://github.com/CocoaPods/trunk.cocoapods.org/pull/124
