### ISSUE TITLE
`pod trunk push` will error if the master spec repository is not present

### ISSUE THREAD

**Issue by kylef** [CocoaPods/cocoapods-trunk#48]
The updating of master spec repository should first create it if necessary.

```shell
$ pod trunk push

[!] Found podspec `Stencil.podspec.json`

pod trunk push returned exit code 1

[!] Unable to find the `master` repo. Action failed: pod trunk push
```

**Comment by segiddins** [comment]
Just replace the update calls with invocations of the setup command. Please make a PR @kylef

**Comment by dkhamsing** [comment]
Hi guys, not sure if this is related.. 

```
$ pod trunk push

[!] Found podspec `FHSTwitterEngine.podspec`
[!] Unable to find the `master` repo.
```
```
$ pod trunk push --verbose

[!] Found podspec `FHSTwitterEngine.podspec`
[!] Unable to find the `master` repo.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/sources_manager.rb:383:in `git_source_named'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/sources_manager.rb:206:in `update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.6.4/lib/pod/command/trunk/push.rb:119:in `update_master_repo'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.6.4/lib/pod/command/trunk/push.rb:58:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

The repo is https://github.com/fhsjaagshs/FHSTwitterEngine .. may have some issues with version?!
How should I proceed

**Comment by segiddins** [comment]
Yes it is. Either make a PR fixing the issue here, or run `pod setup` locally.

**Comment by dkhamsing** [comment]
Oh didn't understand what you meant at first but got it
Thanks
