### ISSUE TITLE
Cannot push to trunk (Internal Server Error)

### ISSUE THREAD

**Issue by gmarm** [CocoaPods/cocoapods-trunk#59]
Hello,

I'm trying to push my updated .podspec to trunk but I'm getting the error below. I've tried different things but cannot seem to tackle the problem.

Here's what I did:
`pod spec lint BetterSegmentedControl.podspec` (validates properly with message: "BetterSegmentedControl.podspec passed validation.")
`pod trunk register <email>` (clicked link from my mail)
`pod trunk push BetterSegmentedControl.podspec --allow-warnings --verbose`. Everything seems fine in the beginning but then I get the error below:
```
opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established
<- "POST /api/v1/pods?allow_warnings=true HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/0.39.0\r\nAuthorization: Token ebdfba63d81719dacd2b0a6b4f3c7c28\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 614\r\n\r\n"
<- "{\"name\":\"BetterSegmentedControl\",\"version\":\"0.2\",\"summary\":\"An easy to use, customizable replacement for UISegmentedControl & UISwitch.\",\"description\":\"BetterSegmentedControl is an easy to use, customizable replacement for UISegmentedControl and UISwitch written in Swift.\",\"homepage\":\"https://github.com/gmarm/BetterSegmentedControl\",\"license\":\"MIT\",\"authors\":{\"George Marmaridis\":\"gmarmas@gmail.com\"},\"source\":{\"git\":\"https://github.com/gmarm/BetterSegmentedControl.git\",\"tag\":0.2},\"social_media_url\":\"https://twitter.com/gmarmas\",\"platforms\":{\"ios\":\"8.0\"},\"requires_arc\":true,\"source_files\":\"Pod/Classes/**/*\"}\n"
-> "HTTP/1.1 500 Internal Server Error\r\n"
-> "Date: Tue, 05 Apr 2016 06:35:29 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 141\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin 1.6.2 codename Doc Brown\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 141 bytes...
-> "{\"error\":\"An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.\"}"
read 141 bytes
Conn keep-alive
[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.6.4/lib/pod/command/trunk.rb:68:in `print_error'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.6.4/lib/pod/command/trunk.rb:28:in `request_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.6.4/lib/pod/command/trunk.rb:34:in `request_path'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.6.4/lib/pod/command/trunk/push.rb:60:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

This is my .podspec:
```
Pod::Spec.new do |s|
  s.name             = "BetterSegmentedControl"
  s.version          = "0.2"
  s.summary          = "An easy to use, customizable replacement for UISegmentedControl & UISwitch."
  s.description      = <<-DESC
BetterSegmentedControl is an easy to use, customizable replacement for UISegmentedControl and UISwitch written in Swift.
                       DESC

  s.homepage         = "https://github.com/gmarm/BetterSegmentedControl"
  # s.screenshots     = "www.example.com/screenshots_1", "www.example.com/screenshots_2"
  s.license          = 'MIT'
  s.author           = { "George Marmaridis" => "gmarmas@gmail.com" }
  s.source           = { :git => "https://github.com/gmarm/BetterSegmentedControl.git", :tag => 0.2 }
  s.social_media_url = 'https://twitter.com/gmarmas'

  s.platform     = :ios, '8.0'
  s.requires_arc = true

  s.source_files = 'Pod/Classes/**/*'
  # s.resource_bundles = {
  #    'BetterSegmentedControl' => ['Pod/Assets/*.png']
  # }

  # s.public_header_files = 'Pod/Classes/**/*.h'
  # s.frameworks = 'UIKit', 'MapKit'
  # s.dependency 'AFNetworking', '~> 2.3'
end
```

CocoaPods version:
`0.39.0` (but I also tried with the latest beta from another computer)

Installed plugins:
```
Installed CocoaPods Plugins:
    - cocoapods-plugins : 0.4.2
    - cocoapods-search  : 0.1.0
    - cocoapods-stats   : 0.6.2 (post_install hook)
    - cocoapods-try     : 0.5.1
    - cocoapods-trunk   : 0.6.4
    - cocoapods-stats   : 0.6.2 (post_install hook)
    - cocoapods-try     : 0.5.1
```

I'm quite new to this so it's probably something that _I_ am doing wrong here.

**Comment by alloy** [comment]
See https://github.com/CocoaPods/trunk.cocoapods.org/pull/177 for some discussion about this.

In the meantime, you can fix your issue by changing the tag to a string:

```ruby
s.source           = { :git => "https://github.com/gmarm/BetterSegmentedControl.git", :tag => "0.2" }
```

**Comment by gmarm** [comment]
@alloy thanks so much. I guess I'm simply blind!
