### ISSUE TITLE
Deprecating a pod with emoji name fails

### ISSUE THREAD

**Issue by neonichu** [CocoaPods/cocoapods-trunk#71]
Might just be a case of generating the correct URL?  ¯\\\_(ツ)\_/¯ 

### Command

```
/usr/local/bin/pod trunk deprecate 🕕
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12 (16A254g)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ 40004aaa5870afdc655bfbbdc84a2718ec8c1805
               autolean - https://github.com/AutoLean/Specs.git @ e607cfbc532d73dd0e3c954ef66279947c0e3987
               bitbucket-agens-agenspodspec - https://bitbucket.org/agens/agenspodspec.git @ 17a2680efb469dd3716a9596d4b7ac36c2ed9072
               contentful - https://github.com/contentful/CocoaPodsSpecs @ b345dbd8ec819403b466678312f5c04e69101726
               danieltomlinson - https://github.com/DanielTomlinson/PersonalSpecs @ 8c01826b09e7dc67d528480bc686844833a9c1ec
               hjanuschka - https://github.com/hjanuschka/mypods.git @ 6dd3a203e6d5820da553dbb4ae96dc4f9851f7f6
               master - https://github.com/CocoaPods/Specs.git @ e5d74c94673bf5de70ada4c9a18ae60cc136c438
               neonichu - https://github.com/neonichu/CocoaPodsSpecs.git @ 799713aed027ea4e4ec38c40d041b1b71b9d7599
               ooyala - https://github.com/ooyala/ios-sdk-podspecs @ de2bc3dac259e4d287a281c1494eef0d03b96da8
               schibsted - https://github.com/schibsted/CocoaPods-Specs.git @ ab7661649dc2d2fe2892515e1785a8806e6573c7
```

### Plugins

```
claide-plugins              : 0.9.0
cocoapods-coverage          : 0.2.0
cocoapods-deintegrate       : 1.0.1
cocoapods-dependencies      : 1.0.0.beta.1
cocoapods-docstats          : 0.0.3
cocoapods-expert-difficulty : 1.0.0
cocoapods-keys              : 1.6.1
cocoapods-packager          : 1.4.0
cocoapods-plugins           : 1.0.0
cocoapods-rome              : 0.7.0
cocoapods-schoutedenapus    : 0.0.1
cocoapods-search            : 1.0.0
cocoapods-stats             : 1.0.0
cocoapods-testing           : 0.2.0
cocoapods-trunk             : 1.0.0
cocoapods-try               : 1.1.0
cocoapods_debug             : 0.1.0
slather                     : 2.2.1
```

### Error

```
URI::InvalidURIError - bad URI(is not URI?): https://trunk.cocoapods.org/api/v1/pods/🕕/deprecated
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:176:in `split'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:211:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:747:in `parse'
/Library/Ruby/Gems/2.0.0/gems/nap-1.1.0/lib/rest.rb:68:in `patch'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk.rb:45:in `create_request'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk.rb:28:in `request_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk.rb:36:in `request_path'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk/deprecate.rb:38:in `deprecate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk/deprecate.rb:30:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
`/Users/segiddins/.rubies/2.3.1/lib/ruby/2.3.0/uri/rfc3986_parser.rb:21:in `split': URI must be ascii only "https://trunk.cocoapods.org/api/v1/pods/\u{1f555}/deprecated" (URI::InvalidURIError)` :sob:

**Comment by segiddins** [comment]
https://github.com/ruby/ruby/commit/b757ff3ef6659ef959a58d15f345f97e19697731

**Comment by orta** [comment]
oh, interesting
