### ISSUE TITLE
Unrecognized `pushed_with_swift_version` key

### ISSUE THREAD

**Issue by ricardopereira** [CocoaPods/cocoapods-trunk#80]
**pod --version:** 1.1.0
**podspec:** https://github.com/whitesmith/WSLogger/blob/master/WSLogger.podspec

**result:**
```
<- "POST /api/v1/pods?allow_warnings=false HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.1.0\r\nAuthorization: Token a9dd38babd855c64fc6d84da2209c868\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 506\r\n\r\n"
<- "{\"name\":\"WSLogger\",\"version\":\"1.0.0\",\"summary\":\"An iOS logger where it's possible to extend the log functionality\",\"homepage\":\"https://github.com/whitesmith/WSLogger\",\"license\":\"MIT\",\"authors\":{\"Ricardo Pereira\":\"m@ricardopereira.eu\"},\"source\":{\"git\":\"https://github.com/whitesmith/WSLogger.git\",\"tag\":\"1.0.0\"},\"social_media_url\":\"https://twitter.com/whitesmithco\",\"platforms\":{\"ios\":\"8.0\"},\"requires_arc\":true,\"source_files\":[\"WSLogger/*.{h}\",\"Source/**/*.{h,swift}\"],\"pushed_with_swift_version\":\"2.2\\n\"}\n"

(...)

-> "{\"error\":\"The Pod Specification did not pass validation.\",\"data\":{\"warnings\":[\"Unrecognized `pushed_with_swift_version` key.\"]}}"
read 128 bytes
Conn keep-alive
[!] The Pod Specification did not pass validation.
The following validation failed:
- Warnings: Unrecognized `pushed_with_swift_version` key.

/Users/ricardopereira/.gem/ruby/2.2.0/gems/cocoapods-trunk-1.1.0/lib/pod/command/trunk.rb:70:in `print_error'
/Users/ricardopereira/.gem/ruby/2.2.0/gems/cocoapods-trunk-1.1.0/lib/pod/command/trunk.rb:30:in `request_url'
/Users/ricardopereira/.gem/ruby/2.2.0/gems/cocoapods-trunk-1.1.0/lib/pod/command/trunk.rb:36:in `request_path'
/Users/ricardopereira/.gem/ruby/2.2.0/gems/cocoapods-trunk-1.1.0/lib/pod/command/trunk/push.rb:79:in `push_to_trunk'
/Users/ricardopereira/.gem/ruby/2.2.0/gems/cocoapods-trunk-1.1.0/lib/pod/command/trunk/push.rb:65:in `run'
/Users/ricardopereira/.gem/ruby/2.2.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/ricardopereira/.gem/ruby/2.2.0/gems/cocoapods-1.1.0/lib/cocoapods/command.rb:50:in `run'
/Users/ricardopereira/.gem/ruby/2.2.0/gems/cocoapods-1.1.0/bin/pod:55:in `<top (required)>'
/Users/ricardopereira/.gem/ruby/2.2.0/bin/pod:22:in `load'
/Users/ricardopereira/.gem/ruby/2.2.0/bin/pod:22:in `<main>'
```

**Comment by ricardopereira** [comment]
Maybe it's related with https://github.com/whitesmith/WSLogger/blob/372138d747ad138fe66289c8bd293fb813775a39/.swift-version

**Comment by segiddins** [comment]
@orta you need to make usage of that method conditional on it being defined

**Comment by ricardopereira** [comment]
I was able to push the release with `--allow-warnings` ¯\_(ツ)_/¯

**Comment by segiddins** [comment]
@orta you need to update trunk to handle the extraneous key in the root-level hash

**Comment by orta** [comment]
Alright - trunk now has https://github.com/CocoaPods/trunk.cocoapods.org/pull/195, people shouldn't be seeing these messages 👍
